/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    documents: Document;
    categories: Category;
    characteristics: Characteristic;
    products: Product;
    orders: Order;
    'vacancy-types': VacancyType;
    'vacancy-categories': VacancyCategory;
    vacancies: Vacancy;
    'vacancy-applications': VacancyApplication;
    'news-categories': NewsCategory;
    news: News;
    'workshop-equipment': WorkshopEquipment;
    services: Service;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    characteristics: CharacteristicsSelect<false> | CharacteristicsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'vacancy-types': VacancyTypesSelect<false> | VacancyTypesSelect<true>;
    'vacancy-categories': VacancyCategoriesSelect<false> | VacancyCategoriesSelect<true>;
    vacancies: VacanciesSelect<false> | VacanciesSelect<true>;
    'vacancy-applications': VacancyApplicationsSelect<false> | VacancyApplicationsSelect<true>;
    'news-categories': NewsCategoriesSelect<false> | NewsCategoriesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    'workshop-equipment': WorkshopEquipmentSelect<false> | WorkshopEquipmentSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ru' | 'en' | 'zh') | ('ru' | 'en' | 'zh')[];
  globals: {
    'site-contacts': SiteContact;
    'labor-protection': LaborProtection;
    'certificates-page': CertificatesPage;
    'education-disclosure': EducationDisclosure;
    procurement: Procurement;
    'services-page': ServicesPage;
    'about-page': AboutPage;
    'home-page': HomePage;
    'workshop-metal-structures': WorkshopMetalStructure;
    'workshop-oilfield-equipment': WorkshopOilfieldEquipment;
    'workshop-building-structures': WorkshopBuildingStructure;
  };
  globalsSelect: {
    'site-contacts': SiteContactsSelect<false> | SiteContactsSelect<true>;
    'labor-protection': LaborProtectionSelect<false> | LaborProtectionSelect<true>;
    'certificates-page': CertificatesPageSelect<false> | CertificatesPageSelect<true>;
    'education-disclosure': EducationDisclosureSelect<false> | EducationDisclosureSelect<true>;
    procurement: ProcurementSelect<false> | ProcurementSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'workshop-metal-structures': WorkshopMetalStructuresSelect<false> | WorkshopMetalStructuresSelect<true>;
    'workshop-oilfield-equipment': WorkshopOilfieldEquipmentSelect<false> | WorkshopOilfieldEquipmentSelect<true>;
    'workshop-building-structures': WorkshopBuildingStructuresSelect<false> | WorkshopBuildingStructuresSelect<true>;
  };
  locale: 'ru' | 'en' | 'zh';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  /**
   * Если пусто — используется имя файла.
   */
  title?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Корневые категории и их slug заданы статически. Названия и порядок можно менять, slug — нет.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Фиксированный адрес категории. Заполняется автоматически при создании.
   */
  slug: string;
  /**
   * Оставьте пустым для корневой категории. Заполните, чтобы сделать подкатегорию.
   */
  parent?: (number | null) | Category;
  /**
   * Картинка подкатегории для слайдера на главной и других блоков каталога.
   */
  image?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Переиспользуемые характеристики товаров. Числовые участвуют в фильтре-диапазоне, текстовые — в фильтре-списке.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characteristics".
 */
export interface Characteristic {
  id: number;
  title: string;
  /**
   * Заполняется автоматически из названия, можно изменить.
   */
  slug?: string | null;
  type: 'number' | 'text';
  unit?: ('none' | 'mm' | 'cm' | 'm' | 'kg' | 't') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Заполняется автоматически из названия, можно изменить.
   */
  slug?: string | null;
  /**
   * Выберите подкатегорию, в которой находится товар.
   */
  category: number | Category;
  availability: 'inStock' | 'onOrder';
  /**
   * Пусто — «цена по запросу».
   */
  price?: number | null;
  /**
   * 0 — без скидки.
   */
  discountPercent?: number | null;
  /**
   * Показывается в каталоге и первым в галерее на странице товара.
   */
  image?: (number | null) | Media;
  /**
   * Дополнительные фото. На странице товара — слайдер с превью; если фото одно, слайдер не показывается.
   */
  gallery?: (number | Media)[] | null;
  /**
   * Используется для сортировки «По популярности».
   */
  popularity?: number | null;
  description?: string | null;
  /**
   * PDF и другие файлы для вкладки «Документация».
   */
  documents?:
    | {
        title: string;
        file: number | Document;
        id?: string | null;
      }[]
    | null;
  /**
   * Добавьте несколько характеристик. Для числовых заполняйте «Значение (число)», для текстовых — «Значение (текст)».
   */
  characteristics?:
    | {
        characteristic: number | Characteristic;
        valueNumber?: number | null;
        valueText?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Необязательно. Технические таблицы на странице товара (под блоком с фото и описанием).
   */
  specTables?:
    | {
        title: string;
        /**
         * Заголовки колонок с данными (без «Параметр»). Оставьте пустым для простой таблицы «параметр — значение».
         */
        columns?:
          | {
              header: string;
              id?: string | null;
            }[]
          | null;
        rows?:
          | {
              kind: 'data' | 'wide' | 'section';
              label?: string | null;
              wideValue?: string | null;
              highlight?: boolean | null;
              accent?: boolean | null;
              /**
               * Одна ячейка на колонку. Несколько значений в ячейке — для многострочных данных.
               */
              cells?:
                | {
                    values?:
                      | {
                          text: string;
                          id?: string | null;
                        }[]
                      | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  name: string;
  phone: string;
  address?: string | null;
  comment?: string | null;
  paymentMethod: 'cardOffice' | 'cashStore';
  status?: ('new' | 'processing' | 'done' | 'cancelled') | null;
  items?:
    | {
        productId?: string | null;
        title: string;
        price?: number | null;
        discountPercent?: number | null;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  subtotal?: number | null;
  discountTotal?: number | null;
  total?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Направления работы для рубрикатора: Офис, Производство, Инженерия и т.д.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vacancy-types".
 */
export interface VacancyType {
  id: number;
  title: string;
  /**
   * Фиксированный адрес категории. Заполняется автоматически при создании.
   */
  slug: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Группы вакансий на главной странице раздела, например «Административно управленческий персонал».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vacancy-categories".
 */
export interface VacancyCategory {
  id: number;
  title: string;
  /**
   * Фиксированный адрес категории. Заполняется автоматически при создании.
   */
  slug: string;
  type: number | VacancyType;
  description?: string | null;
  /**
   * Минимальная зарплата для отображения на карточке категории.
   */
  salaryFrom?: number | null;
  image?: (number | null) | Media;
  publishedAt?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vacancies".
 */
export interface Vacancy {
  id: number;
  title: string;
  /**
   * Заполняется автоматически из названия, можно изменить.
   */
  slug?: string | null;
  /**
   * Краткое уточнение для формы отклика и карточки.
   */
  subtitle?: string | null;
  /**
   * Краткое описание обязанностей и требований для карточки вакансии.
   */
  description?: string | null;
  category: number | VacancyCategory;
  /**
   * Отдельная привязка к типу для фильтрации в рубрикаторе.
   */
  type: number | VacancyType;
  salaryFrom?: number | null;
  /**
   * Необязательно. Если задано, выводится вместо «От N ₽».
   */
  salaryText?: string | null;
  schedule?: string | null;
  experience?: string | null;
  /**
   * Например: г. Очёр, ул. Малышева, 1
   */
  location?: string | null;
  /**
   * Основной текст страницы вакансии: заголовки, списки, изображения и блоки в две колонки.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  isActive?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Заявки кандидатов с привязкой к конкретной вакансии.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vacancy-applications".
 */
export interface VacancyApplication {
  id: number;
  vacancy: number | Vacancy;
  /**
   * Сохраняется при отправке отклика для истории.
   */
  vacancyTitle: string;
  categoryTitle?: string | null;
  applicantName: string;
  phone: string;
  about: string;
  resume?: (number | null) | Document;
  status?: ('new' | 'viewed' | 'contacted' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Рубрики пресс-центра: «Жизнь завода», «Производство» и другие. Фильтр «все» на сайте не требует отдельной записи.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-categories".
 */
export interface NewsCategory {
  id: number;
  title: string;
  /**
   * Фиксированный адрес категории. Заполняется автоматически при создании.
   */
  slug: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * Заполняется автоматически из названия, можно изменить.
   */
  slug?: string | null;
  /**
   * Текст для карточки новости в списке и на главной.
   */
  description?: string | null;
  /**
   * Превью в сетке и карусели новостей.
   */
  image?: (number | null) | Media;
  category: number | NewsCategory;
  /**
   * Полный текст: заголовки, списки, изображения, видео, выделение и цветовое форматирование.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  isActive?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshop-equipment".
 */
export interface WorkshopEquipment {
  id: number;
  /**
   * Цех, к которому относится единица оборудования.
   */
  workshop: 'metal-structures' | 'oilfield-equipment' | 'building-structures';
  /**
   * Короткое название для карточки в парке оборудования.
   */
  title: string;
  /**
   * Развёрнутое название для попапа. Если не заполнено — используется краткий заголовок.
   */
  titleFull?: string | null;
  /**
   * Короткий текст для карточки и левой колонки попапа.
   */
  description: string;
  /**
   * Полный текст для правой колонки попапа «Подробнее».
   */
  descriptionLong: string;
  /**
   * Пункты с красной галочкой в попапе.
   */
  features?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  image: number | Media;
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Используется в URL, например pump-rods-repair
   */
  slug: string;
  description: string;
  image: number | Media;
  heroTitle?: string | null;
  heroDescription?: string | null;
  heroImage?: (number | null) | Media;
  pageContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  advantages?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'characteristics';
        value: number | Characteristic;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'vacancy-types';
        value: number | VacancyType;
      } | null)
    | ({
        relationTo: 'vacancy-categories';
        value: number | VacancyCategory;
      } | null)
    | ({
        relationTo: 'vacancies';
        value: number | Vacancy;
      } | null)
    | ({
        relationTo: 'vacancy-applications';
        value: number | VacancyApplication;
      } | null)
    | ({
        relationTo: 'news-categories';
        value: number | NewsCategory;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'workshop-equipment';
        value: number | WorkshopEquipment;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characteristics_select".
 */
export interface CharacteristicsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  unit?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  availability?: T;
  price?: T;
  discountPercent?: T;
  image?: T;
  gallery?: T;
  popularity?: T;
  description?: T;
  documents?:
    | T
    | {
        title?: T;
        file?: T;
        id?: T;
      };
  characteristics?:
    | T
    | {
        characteristic?: T;
        valueNumber?: T;
        valueText?: T;
        id?: T;
      };
  specTables?:
    | T
    | {
        title?: T;
        columns?:
          | T
          | {
              header?: T;
              id?: T;
            };
        rows?:
          | T
          | {
              kind?: T;
              label?: T;
              wideValue?: T;
              highlight?: T;
              accent?: T;
              cells?:
                | T
                | {
                    values?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  address?: T;
  comment?: T;
  paymentMethod?: T;
  status?: T;
  items?:
    | T
    | {
        productId?: T;
        title?: T;
        price?: T;
        discountPercent?: T;
        quantity?: T;
        id?: T;
      };
  subtotal?: T;
  discountTotal?: T;
  total?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vacancy-types_select".
 */
export interface VacancyTypesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vacancy-categories_select".
 */
export interface VacancyCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  description?: T;
  salaryFrom?: T;
  image?: T;
  publishedAt?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vacancies_select".
 */
export interface VacanciesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  description?: T;
  category?: T;
  type?: T;
  salaryFrom?: T;
  salaryText?: T;
  schedule?: T;
  experience?: T;
  location?: T;
  content?: T;
  publishedAt?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vacancy-applications_select".
 */
export interface VacancyApplicationsSelect<T extends boolean = true> {
  vacancy?: T;
  vacancyTitle?: T;
  categoryTitle?: T;
  applicantName?: T;
  phone?: T;
  about?: T;
  resume?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-categories_select".
 */
export interface NewsCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  image?: T;
  category?: T;
  content?: T;
  publishedAt?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshop-equipment_select".
 */
export interface WorkshopEquipmentSelect<T extends boolean = true> {
  workshop?: T;
  title?: T;
  titleFull?: T;
  description?: T;
  descriptionLong?: T;
  features?:
    | T
    | {
        text?: T;
        id?: T;
      };
  image?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  image?: T;
  heroTitle?: T;
  heroDescription?: T;
  heroImage?: T;
  pageContent?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  advantages?:
    | T
    | {
        text?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-contacts".
 */
export interface SiteContact {
  id: number;
  /**
   * Отображается в шапке и мобильном меню.
   */
  headerPhone: string;
  headerEmail: string;
  hotlinePhone: string;
  hotlineEmail: string;
  /**
   * Блок «Почта» в подвале.
   */
  generalEmail: string;
  commercialEmail: string;
  /**
   * Каждая строка отображается отдельно.
   */
  workingHours?: string | null;
  /**
   * Контактные телефоны по городам для подвала и страницы контактов.
   */
  offices?:
    | {
        city: string;
        phone: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "labor-protection".
 */
export interface LaborProtection {
  id: number;
  documents?:
    | {
        file: number | Document;
        title: string;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates-page".
 */
export interface CertificatesPage {
  id: number;
  items?:
    | {
        slug: string;
        image: number | Media;
        title: string;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education-disclosure".
 */
export interface EducationDisclosure {
  id: number;
  pageTitle: string;
  /**
   * Секции и строки таблицы. Для типа «Ссылка» и «Кнопки» красное оформление и скачивание появляются только при прикреплённом файле.
   */
  entries?:
    | {
        kind: 'section' | 'row';
        sectionTitle?: string | null;
        titleStyle?: ('default' | 'compact') | null;
        code?: string | null;
        name?: string | null;
        infoType?: ('text' | 'link' | 'buttons') | null;
        lines?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Если файл прикреплён, текст отображается красной ссылкой со скачиванием.
         */
        file?: (number | null) | Document;
        /**
         * Без файла элемент показывается обычным текстом. С файлом — кнопкой для скачивания.
         */
        buttons?:
          | {
              label: string;
              variant?: ('filled' | 'outline') | null;
              file?: (number | null) | Document;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "procurement".
 */
export interface Procurement {
  id: number;
  pageTitle: string;
  /**
   * Порядковый номер проставляется автоматически. Для группы укажите заголовок без номера (например, «Дробь:») и несколько позиций с количеством.
   */
  entries?:
    | {
        kind: 'group' | 'row';
        /**
         * Без номера — на сайте будет «1. Дробь:», «2. …» и т.д.
         */
        groupTitle?: string | null;
        items?:
          | {
              name: string;
              quantity?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Без номера — номер добавится на сайте автоматически.
         */
        name?: string | null;
        quantity?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: number;
  pageTitle: string;
  cardsSectionTitle: string;
  bottomContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  /**
   * Rich-текст под блоком каталога: заголовки, списки, видео и выделенные блоки.
   */
  bottomContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * Текстовый блок внизу главной: заголовки, списки, видео, выделенные блоки и цветовое форматирование.
   */
  aboutContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Страница /production/metal-structures — hero, порядок секций, контент. Оборудование — в коллекции «Парк оборудования».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshop-metal-structures".
 */
export interface WorkshopMetalStructure {
  id: number;
  heroDescription?: string | null;
  heroBackground?: (number | null) | Media;
  /**
   * Перетаскивайте строки, чтобы изменить порядок блоков на странице. Каждый тип секции можно использовать один раз.
   */
  sectionOrder?:
    | {
        section: 'about' | 'stock' | 'equipment' | 'advantages';
        id?: string | null;
      }[]
    | null;
  /**
   * Rich text: заголовки, текст, слайдер изображений, видео, callout.
   */
  aboutContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Слайдер карточек с фоновым изображением, заголовком и значением (например, «290 м.п.»).
   */
  stockSection?: {
    /**
     * Заполняйте, если секция «Складской остаток» включена в порядок секций.
     */
    title?: string | null;
    items?:
      | {
          title: string;
          /**
           * Например: 290 м.п.
           */
          value: string;
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Карточки («Передовое оснащение» и др.). Количество произвольное.
   */
  advantageBlocks?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Страница /production/oilfield-equipment — hero, порядок секций, контент. Оборудование — в коллекции «Парк оборудования».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshop-oilfield-equipment".
 */
export interface WorkshopOilfieldEquipment {
  id: number;
  heroDescription?: string | null;
  heroBackground?: (number | null) | Media;
  /**
   * Перетаскивайте строки, чтобы изменить порядок блоков на странице. Каждый тип секции можно использовать один раз.
   */
  sectionOrder?:
    | {
        section: 'about' | 'stock' | 'equipment' | 'advantages';
        id?: string | null;
      }[]
    | null;
  /**
   * Rich text: заголовки, текст, слайдер изображений, видео, callout.
   */
  aboutContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Слайдер карточек с фоновым изображением, заголовком и значением (например, «290 м.п.»).
   */
  stockSection?: {
    /**
     * Заполняйте, если секция «Складской остаток» включена в порядок секций.
     */
    title?: string | null;
    items?:
      | {
          title: string;
          /**
           * Например: 290 м.п.
           */
          value: string;
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Карточки («Передовое оснащение» и др.). Количество произвольное.
   */
  advantageBlocks?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Страница /production/building-structures — hero, порядок секций, контент. Оборудование — в коллекции «Парк оборудования».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshop-building-structures".
 */
export interface WorkshopBuildingStructure {
  id: number;
  heroDescription?: string | null;
  heroBackground?: (number | null) | Media;
  /**
   * Перетаскивайте строки, чтобы изменить порядок блоков на странице. Каждый тип секции можно использовать один раз.
   */
  sectionOrder?:
    | {
        section: 'about' | 'stock' | 'equipment' | 'advantages';
        id?: string | null;
      }[]
    | null;
  /**
   * Rich text: заголовки, текст, слайдер изображений, видео, callout.
   */
  aboutContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Слайдер карточек с фоновым изображением, заголовком и значением (например, «290 м.п.»).
   */
  stockSection?: {
    /**
     * Заполняйте, если секция «Складской остаток» включена в порядок секций.
     */
    title?: string | null;
    items?:
      | {
          title: string;
          /**
           * Например: 290 м.п.
           */
          value: string;
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Карточки («Передовое оснащение» и др.). Количество произвольное.
   */
  advantageBlocks?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-contacts_select".
 */
export interface SiteContactsSelect<T extends boolean = true> {
  headerPhone?: T;
  headerEmail?: T;
  hotlinePhone?: T;
  hotlineEmail?: T;
  generalEmail?: T;
  commercialEmail?: T;
  workingHours?: T;
  offices?:
    | T
    | {
        city?: T;
        phone?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "labor-protection_select".
 */
export interface LaborProtectionSelect<T extends boolean = true> {
  documents?:
    | T
    | {
        file?: T;
        title?: T;
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates-page_select".
 */
export interface CertificatesPageSelect<T extends boolean = true> {
  items?:
    | T
    | {
        slug?: T;
        image?: T;
        title?: T;
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education-disclosure_select".
 */
export interface EducationDisclosureSelect<T extends boolean = true> {
  pageTitle?: T;
  entries?:
    | T
    | {
        kind?: T;
        sectionTitle?: T;
        titleStyle?: T;
        code?: T;
        name?: T;
        infoType?: T;
        lines?:
          | T
          | {
              text?: T;
              id?: T;
            };
        file?: T;
        buttons?:
          | T
          | {
              label?: T;
              variant?: T;
              file?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "procurement_select".
 */
export interface ProcurementSelect<T extends boolean = true> {
  pageTitle?: T;
  entries?:
    | T
    | {
        kind?: T;
        groupTitle?: T;
        items?:
          | T
          | {
              name?: T;
              quantity?: T;
              id?: T;
            };
        name?: T;
        quantity?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  pageTitle?: T;
  cardsSectionTitle?: T;
  bottomContent?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  bottomContent?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  aboutContent?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshop-metal-structures_select".
 */
export interface WorkshopMetalStructuresSelect<T extends boolean = true> {
  heroDescription?: T;
  heroBackground?: T;
  sectionOrder?:
    | T
    | {
        section?: T;
        id?: T;
      };
  aboutContent?: T;
  stockSection?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              title?: T;
              value?: T;
              image?: T;
              id?: T;
            };
      };
  advantageBlocks?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshop-oilfield-equipment_select".
 */
export interface WorkshopOilfieldEquipmentSelect<T extends boolean = true> {
  heroDescription?: T;
  heroBackground?: T;
  sectionOrder?:
    | T
    | {
        section?: T;
        id?: T;
      };
  aboutContent?: T;
  stockSection?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              title?: T;
              value?: T;
              image?: T;
              id?: T;
            };
      };
  advantageBlocks?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workshop-building-structures_select".
 */
export interface WorkshopBuildingStructuresSelect<T extends boolean = true> {
  heroDescription?: T;
  heroBackground?: T;
  sectionOrder?:
    | T
    | {
        section?: T;
        id?: T;
      };
  aboutContent?: T;
  stockSection?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              title?: T;
              value?: T;
              image?: T;
              id?: T;
            };
      };
  advantageBlocks?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}